### ISSUE TITLE
Emitted HLSL contains many unneeded new lines

### ISSUE THREAD

**Issue by jeremyong-az** [o3de/o3de-azslc#57]
```
// HLSL emission by AZSL Compiler 1.7.35 Win64
#line 14 "D:/o3de-atom-sampleviewer/user/AssetProcessorTemp/JobTemp-KiBTnM/StandardPBR_ForwardPass.azsl.dx12.prepend"


















static const float4 s_AzslDebugColor = float4 ( 16.0 / 255.0 , 124.0 / 255.0 , 16.0 / 255.0 , 1 ) ;
#line 11 "D:/o3de/Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/SrgSemantics.azsli"
#line 13 "D:/o3de/Gems/Atom/Feature/Common/Assets/ShaderResourceGroups/Decals/ViewSrg.azsli"














```

For example ^.

The new lines here corresponded to stripped comments, but instead of emitting new lines, we should just be adjusting the first argument of those `#line` directives.

**Comment by siliconvoodoo** [comment]
Wouldn't it be better to preserve the comments? That would give some landmarks to authors who can navigate their code by familiarity, or leave anchors to search for. Especially in case of wrong line reporting, because of potential miss in the line directives (not unheard-of). I don't remember why we chose to remove them, it's possible that the reason is as simple as they just get skipped by AntlR's lexer, and we never made the effort of recovering them.

**Comment by jeremyong-az** [comment]
@siliconvoodoo There are two reasons I can think of for stripping comments.

1. If we cache the preprocessed HLSL as an intermediate asset (something @santorac is prototyping), cached shader binaries would not be affected by either dead code (stripped via pound-def) _or_ comments. If we strip unused functions from HLSL in the future, the comments associated with those functions would persist also.
2. Really fat shaders sometimes don't work well with tools that do source analysis (e.g. Pix or Nsight), but I've noticed this has improved quite a bit in recent years

It may be useful to have an option to preserve them however.

**Comment by siliconvoodoo** [comment]
fair!

btw I found the likely culprit for the empty lines, I suspect commit 396d653f

Also I'm noting bugs in line directive generation (that we should be relying on instead of empty lines btw).
![image](https://user-images.githubusercontent.com/25970839/190055490-b6b77755-2c51-4c51-bcfa-4d46035dd065.png)
This might relate to bug https://github.com/o3de/o3de-azslc/issues/39

**Comment by siliconvoodoo** [comment]
Ok I have a fix. (commit b3518ad1adacd87e4f4676992da00d8bac6f5796)
Before:
![image](https://user-images.githubusercontent.com/25970839/190983247-509af324-cd1e-43d6-a305-12f712f5e96b.png)

In between (change to a line emission system rather than line feeds)
![image](https://user-images.githubusercontent.com/25970839/190982934-5d497be0-db6e-4796-96aa-6c1e5a72a940.png)

After improvement with "line economy" (only reemit when out of sync)
![image](https://user-images.githubusercontent.com/25970839/190982835-a50a5cf4-6c1c-496a-941c-10459b4fad9f.png)

Example2:
![image](https://user-images.githubusercontent.com/25970839/190983146-8e314e5e-6e7a-4ebb-a142-0ada83628cb1.png)

**Comment by siliconvoodoo** [comment]
Submitted in #61
